# Generated by Django 2.0 on 2020-05-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendorcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'Vendorcategory',
            },
        ),
        migrations.CreateModel(
            name='Vendordetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='images/')),
                ('location', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Vendordetail',
            },
        ),
    ]
