# Generated by Django 2.0 on 2020-05-10 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_vendorcategory_vendordetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetail',
            name='vcategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='planner.Vendorcategory'),
        ),
    ]
